language: python
python:
  - "3.6"

env:
  - SECRET_KEY='mashedpotatoes' DATABASE_NAME='django_lender' DATABASE_USER='postgres' DATABASE_HOST="127.0.0.1" DATABASE_PASSWORD=''

install:
  - pip install -r requirements.pip

services:
  - postgresql

before_script:
  - psql -c "create database django_lender;" -U postgres

script: 
  - python django_imager/manage.py migrate
  - python django_imager/manage.py test
