language: python
python:
  - "3.6"

env:
  - SECRET_KEY='mashedpotatoes'

install:
  - pip install -r requirements.pip

services:
  - postgresql 

script: python django_imager/manage.py test --noinput